# Generated by Django 4.2.7 on 2023-12-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('kanbans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
