# Generated by Django 4.2.7 on 2023-12-05 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanbans', '0002_alter_column_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='작업제목')),
                ('order', models.IntegerField(verbose_name='작업순서')),
                ('tag', models.CharField(choices=[('Backend', 'BE'), ('Frontend', 'FE'), ('Design', 'Design'), ('QA', 'QA'), ('PM', 'PM'), ('Document', 'Document')], max_length=100, verbose_name='태그')),
                ('deadline', models.DateField(verbose_name='작업기한')),
                ('workload', models.FloatField(verbose_name='작업시간(H)')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanbans.column')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
